[tool.poetry]
name = "BiscuIT-App-SchILD-NRW"
version = "1.0a4.dev0"
packages = [
    { include = "biscuit" }
]
readme = "README.rst"

description = "BiscuIT School Information System (SIS) - App for SchILD-NRW interaction"
authors = ["Dominik George <dominik.george@teckids.org>"]
license = "EUPL-1.2"
homepage = "https://biscuit.edugit.io/"
repository = "https://edugit.org/BiscuIT/BiscuIT-App-SchILD-NRW"
documentation = "https://biscuit.edugit.io/BiscuIT-ng/docs/html/"
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Education",
    "Topic :: Education"
]

[tool.poetry.dependencies]
python = "^3.7"
BiscuIT-ng = {version = "^1.0a3.dev0", allows-prereleases = true, path = "../../.."}
pandas = "^0.25.0"
phonenumbers = "^8.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
