[tool.poetry]
name = "BiscuIT-App-SchILD-NRW"
version = "1.0a0"
packages = [
    { include = "biscuit" }
]
readme = "README.md"

description = "BiscuIT School Information System (SIS) - App SchILD-NRW (SchILD-NRW import)"
authors = ["BiscuIT Team <biscuit-dev@lists.teckids.org>"]
license = "MIT"
homepage = "https://biscuit.edugit.org/"
repository = "https://edugit.org/Teckids/BiscuIT/BiscuIT-App-SchILD-NRW"
documentation = "https://biscuit.edugit.org/docs/html/"
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Education",
    "Topic :: Education"
]

[tool.poetry.dependencies]
python = "^3.7"
BiscuIT-ng = {version = "^1.0a0", allows-prereleases = true, path = "../../.."}
pandas = "^0.25.0"
phonenumbers = "^8.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
