# Generated by Django 3.0.6 on 2020-06-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("csv_import", "0003_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="importtemplate",
            name="group_type",
            field=models.ForeignKey(
                blank=True,
                help_text="If imported objects are groups, they all will get this group type after import.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.GroupType",
                verbose_name="Group type",
            ),
        ),
    ]
